services:
  app:
    profiles:
      - prod
    build: .
    container_name: app
    command: python src/main.py
    environment:
      - REPOSITORY_URL=https://github.com/benramort/Spootify
      - THRESHOLD=0.7
      - NEW_HEURISTIC=False
    volumes:
      - .:/app

  test:
    profiles:
      - test
    build: .
    container_name: test
    command: ["sh", "-c", "pytest && coverage run -m pytest && coverage xml && coverage html"]
    environment:
      - PYTHONPATH=/app/src
      - THRESHOLD=0.7
    volumes:
      - .:/app