services:
  app:
    profiles:
      - prod
    build: .
    container_name: app
    command: python src/main.py
    volumes:
      - .:/app

  test:
    profiles:
      - test
    build: .
    container_name: test
    command: ["sh", "-c", "pytest && coverage run -m pytest && coverage xml && coverage html"]
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app